appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mX5puzhi0XXkGySh9YrJiDnM8FE3zab7xprL+Vi8GUjQVGbEKu8TkBIGmFsu7MQax7BV0Me53Jkvef7XmGYgNg2jPH38fqAQ00FG2nrZwGZOT/xyNOrCbLK/prPnUDLTC40njprVE0scs9YqLOyur0KW48zj3LXpwSbZRq4U/YJF9+lmHZkAcWAMWwmh7vsiYxi7XokHKGGhzUZdT6MSKcMHz886oNsdXFgLRwH5nU8eJMqYqFOqSK4BOAmB6AaW/mz1pn6jShTA3H24L6rukGdH8NsBKOu9NAz2stLpHfcN5BjIT4wVAtiwc57EY6q4evohwnQePXKHOFae+alU5R2x8IQlU3M5JDGgKtgbLmtvSKga1qDxF93SlF+aHO5PwR+dICISuNmYlaSPiceo0quAKy9ZI/sqJP3c/eGLw7V5/+FLSd441lgoGY1DbGwI+me34tys1dROr1o9iBBzRc+f5ZJYvMq0KZmqqw6cltU3n3767WJIqDGSnPqxGq3/dhTa8NLhx+/YEUF/Y7wEeWH5cmomnVAZf985xhKniJXCCl3DbX3SUPh6/DcNbnciYtte4ktj6nmGhARxeZ5q5Zn+X0EnhTDLHKqxW84gN6XKXgnS8yt0VREWz7TodEyHZY/eESTcTCRJ0EbT7M4PoKclUO5HCJdDEiGcvcbgYHI=}
